### ISSUE TITLE
Unknown FIle error

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#49] opened 2015-11-06 18:18 UTC
@ilogue I think this was expected re:upstream file(s) that was never reaped/discovered but later operated on. It looks lik `listener.unknownFile` is being called on a parent file for reason that is unclear to me.

>Traceback (most recent call last):
  File "/home/kambiz/pythonistan/ilabs/scripts/analysis.py", line 162, in <module>
    print_status=False
  File "/home/kambiz/anaconda/lib/python2.7/site-packages/mnefun/_mnefun.py", line 512, in do_processing
    p.on_process(text, func, outs[ii], p)
  File "/home/kambiz/anaconda/lib/python2.7/site-packages/niprov-0.2.1-py2.7.egg/niprov/mnefunsupport.py", line 54, in handler
    log(pcafile, trans, sssfile, provenance=customprov)
  File "/home/kambiz/anaconda/lib/python2.7/site-packages/niprov-0.2.1-py2.7.egg/niprov/logging.py", line 77, in log
    listener.unknownFile(parents[0])
  File "/home/kambiz/anaconda/lib/python2.7/site-packages/niprov-0.2.1-py2.7.egg/niprov/commandline.py", line 35, in unknownFile
    raise UnknownFileError('Unknown file: '+fpath)
niprov.exceptions.UnknownFileError: Unknown file: /media/ALAYA/data/ilabs/shiva/meg/shiva_1081/sss_fif/shiva_1081_a_raw_sss.fif

**Comment by ilogue** [comment] 2016-01-27 00:21
@kambysese do you have time to look at this together this week?

**Comment by ilogue** [comment] 2016-02-08 23:12
Duplicate of #96

**Closed by ilogue** 2016-02-08 23:12 UTC
Labels: bug
